#requires -Version 7.4

Import-Module Pester -MinimumVersion 5.5 -ErrorAction Stop

Describe 'Docs site' -Tag 'Docs' {
    BeforeAll {
        $repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
        $docsRoot = Join-Path $repoRoot 'docs'
        if (-not (Test-Path $docsRoot)) {
            throw "Docs folder not found at $docsRoot"
        }

        $bundleCmd = (Get-Command bundle -ErrorAction Stop).Source
        Push-Location $docsRoot
        try {
            $buildArgs = @('exec', 'jekyll', 'build', '--quiet')
            $buildOutput = & $bundleCmd $buildArgs 2>&1
            $exitCode = $LASTEXITCODE
        } finally {
            Pop-Location
        }

        $siteRoot = Join-Path $docsRoot '_site'
        $indexPath = Join-Path $siteRoot 'index.html'
        $indexHtml = if (Test-Path $indexPath) { Get-Content -Path $indexPath -Raw } else { '' }

        $script:DocsTestData = [pscustomobject]@{
            RepoRoot      = $repoRoot
            DocsRoot      = $docsRoot
            SiteRoot      = $siteRoot
            BuildExitCode = $exitCode
            BuildOutput   = ($buildOutput -join [Environment]::NewLine)
            IndexHtml     = $indexHtml
            Pages         = @(
                'index.html'
                'cmdlets/Get-Snippet.html'
                'cmdlets/Invoke-Snippet.html'
                'cmdlets/New-Snippet.html'
                'cmdlets/Set-Snippet.html'
                'cmdlets/Remove-Snippet.html'
                'cmdlets/Export-Snippet.html'
                'cmdlets/Export-SnippetToMarkdown.html'
            )
        }

        $script:DocsTestData | Add-Member -NotePropertyName NavLinks -NotePropertyValue (
            $script:DocsTestData.Pages | ForEach-Object { '/{0}' -f ($_ -replace '\\', '/') }
        )
    }

    It 'runs bundle exec jekyll build successfully' {
        if ($script:DocsTestData.BuildExitCode -ne 0) {
            Write-Warning $script:DocsTestData.BuildOutput
        }
        $script:DocsTestData.BuildExitCode | Should -Be 0
    }

    It 'creates the _site output directory' {
        Test-Path $script:DocsTestData.SiteRoot | Should -BeTrue
    }

    It 'generates <Page>' -TestCases $script:DocsTestData.Pages {
        param([string]$Page)
        $targetPath = Join-Path $script:DocsTestData.SiteRoot $Page
        Test-Path $targetPath | Should -BeTrue -Because "Expected $Page to be generated by Jekyll build"
    }

    It 'exposes nav link for <Link>' -TestCases $script:DocsTestData.NavLinks {
        # Suppress quote fixes by VSCode in this scriptblock only
        [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseConsistentQuotes','', Justification='Regex literal requires specific quoting')]
        [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingDoubleQuotesForConstantString','')]
        param([string]$Link)
        $expected = [regex]::Escape(("href=`"{0}`"" -f $Link))
        $script:DocsTestData.IndexHtml | Should -Match $expected
    }
}
