source "https://rubygems.org"

# Local site uses the same theme/plugins as GitHub Pages
ruby "3.2.10"
# Note: GitHub Actions ubuntu-latest runners use Ruby 3.2.x

# Core site generator and theme
gem "jekyll", "~> 4.3"
#gem "jekyll-theme-primer"
gem "webrick", "~> 1.8"
gem "minima", "~> 2.5"

# Plugins referenced in _config.yml
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-seo-tag", "~> 2.8"
end
