source "https://rubygems.org"

# Local site uses the same theme/plugins as GitHub Pages
ruby "4.0.1"

# Core site generator and theme
gem "jekyll", "~> 4.3"
#gem "jekyll-theme-primer"
gem "webrick", "~> 1.8"

# Plugins referenced in _config.yml
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "minima", "~> 2.5"
end
